apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/amllan-b/argo-cd.git
    targetRevision: HEAD
    path: alloy
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd  # Creates the Application resource in argocd namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
