# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: prometheus-app
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/amllan-b/argo-cd.git
#     targetRevision: main
#     path: prometheus
#     directory:
#       recurse: false
#       include: 'app.yaml'  # Only include app.yaml, ignore values.yaml
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: argocd
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
